### ISSUE TITLE
Task "Ensure Homebrew is installed" Failing

### ISSUE THREAD

**Issue by zharbour** [geerlingguy/ansible-collection-mac#23]
Performing an ansible run on a single VM running 11.4 (Big Sur). This is a fresh VM, nothing else installed. Port forwarding has been configured. 

The ansible files are simple as to just test the roles work as intended over the configured ssh connection.

### playbook.yml
```yaml
---
- name: Golden image configuration
  hosts: packer

  vars:
    homebrew_installed_packages:
      - git
      - openjdk@8

  roles:
    - geerlingguy.mac.homebrew
```

### requirements.yml
```yaml
---
roles:
  - name: elliotweiser.osx-command-line-tools

collections:
  - name: geerlingguy.mac
```

### inventory
```
[packer]
127.0.0.1 ansible_ssh_pass=***** ansible_user=***** ansible_port=10000
```

`TASK [geerlingguy.mac.homebrew : Ensure Homebrew is installed.]` just craps out, and with `-vvvv` I get the following traceback. 
```
The full traceback is:
Traceback (most recent call last):
  File "/Users/anka/.ansible/tmp/ansible-tmp-1633819721.422527-15747-48633493768772/AnsiballZ_git.py", line 100, in <module>
    _ansiballz_main()
  File "/Users/anka/.ansible/tmp/ansible-tmp-1633819721.422527-15747-48633493768772/AnsiballZ_git.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/anka/.ansible/tmp/ansible-tmp-1633819721.422527-15747-48633493768772/AnsiballZ_git.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/f0/r0_px1z90y14c9r4ts7nt20m0000gn/T/ansible_git_payload_DkMYht/ansible_git_payload.zip/ansible/modules/git.py", line 1333, in <module>
  File "/var/folders/f0/r0_px1z90y14c9r4ts7nt20m0000gn/T/ansible_git_payload_DkMYht/ansible_git_payload.zip/ansible/modules/git.py", line 1214, in main
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py", line 296, in __cmp__
    return cmp(self.version, other.version)
AttributeError: 'NoneType' object has no attribute 'version'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/Users/anka/.ansible/tmp/ansible-tmp-1633819721.422527-15747-48633493768772/AnsiballZ_git.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/Users/anka/.ansible/tmp/ansible-tmp-1633819721.422527-15747-48633493768772/AnsiballZ_git.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/Users/anka/.ansible/tmp/ansible-tmp-1633819721.422527-15747-48633493768772/AnsiballZ_git.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 188, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/var/folders/f0/r0_px1z90y14c9r4ts7nt20m0000gn/T/ansible_git_payload_DkMYht/ansible_git_payload.zip/ansible/modules/git.py\", line 1333, in <module>\r\n  File \"/var/folders/f0/r0_px1z90y14c9r4ts7nt20m0000gn/T/ansible_git_payload_DkMYht/ansible_git_payload.zip/ansible/modules/git.py\", line 1214, in main\r\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/version.py\", line 296, in __cmp__\r\n    return cmp(self.version, other.version)\r\nAttributeError: 'NoneType' object has no attribute 'version'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

Might be difficult to replicate this unless you have access to an environment running Anka. That is what I'm using to create the VM. Hopefully it's just a simple oversight on my end.

**Comment by geerlingguy** [comment]
`AttributeError: 'NoneType' object has no attribute 'version'` usually either means your Ansible version is too old (2.9 or later is recommended), or your Python version is too old (3.6 or later is recommended)—most likely the latter.

**Comment by geerlingguy** [comment]
@zharbour - It's weird, because in the playbook output, I'm seeing:

```
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
```

Which seems to indicate when you run `ansible-playbook` it's picking up Python 2.7.
