### ISSUE TITLE
TypeError during Homebrew Cask Installation of android-platform-tools on MacOS

### ISSUE THREAD

**Issue by mark-omarov** [geerlingguy/ansible-collection-mac#92]
Since one of the recent updates I'm receiving the following:
`TypeError: '<' not supported between instances of 'str' and 'int'` on `android-platform-tools` installation with `homebrew_cask_apps`.

```yml
homebrew_cask_apps:
  - { name: 'android-platform-tools', install_options: 'quiet' }
```

Controller node's OS: MacOS Ventura (local) and Ubuntu Latest (GitHub Runner)
Target OS: MacOS Mojave (remote)
Ansible version:
```
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/Users/mark.omarov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mark.omarov/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/mark.omarov/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/mark.omarov/.pyenv/versions/3.11.1/bin/ansible
  python version = 3.11.1 (main, May 17 2023, 07:54:20) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/mark.omarov/.pyenv/versions/3.11.1/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

<details>
<summary>Detailed Log</summary>
TASK [geerlingguy.mac.homebrew : Install configured cask applications.] ****************************************************************************
task path: /<user-home-dir>/.ansible/collections/ansible_collections/geerlingguy/mac/roles/homebrew/tasks/main.yml:136
redirecting (type: modules) ansible.builtin.homebrew_cask to community.general.homebrew_cask
<<host-ip>> ESTABLISH SSH CONNECTION FOR USER: <user>
<<host-ip>> SSH: EXEC sshpass -d52 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="<user>"' -o ConnectTimeout=10 -o 'ControlPath="<user-home-dir>.ansible/cp/8293f2b576"' <host-ip> '/bin/sh -c '"'"'echo ~<user> && sleep 0'"'"''
<<host-ip>> (0, b'/Users/<user>\n', b'')
<<host-ip>> ESTABLISH SSH CONNECTION FOR USER: <user>
<<host-ip>> SSH: EXEC sshpass -d52 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="<user>"' -o ConnectTimeout=10 -o 'ControlPath="<user-home-dir>.ansible/cp/8293f2b576"' <host-ip> '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /Users/<user>/.ansible/tmp `"&& mkdir "` echo /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751 `" && echo ansible-tmp-1708063976.388025-51090-165256968901751="` echo /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751 `" ) && sleep 0'"'"''
<<host-ip>> (0, b'ansible-tmp-1708063976.388025-51090-165256968901751=/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751\n', b'')
redirecting (type: modules) ansible.builtin.homebrew_cask to community.general.homebrew_cask
Using module file <user-home-dir>.ansible/collections/ansible_collections/community/general/plugins/modules/homebrew_cask.py
<<host-ip>> PUT <user-home-dir>.ansible/tmp/ansible-local-50566tfckrair/tmpt7vkfxm_ TO /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py
<<host-ip>> SSH: EXEC sshpass -d52 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="<user>"' -o ConnectTimeout=10 -o 'ControlPath="<user-home-dir>.ansible/cp/8293f2b576"' '[<host-ip>]'
<<host-ip>> (0, b'sftp> put <user-home-dir>.ansible/tmp/ansible-local-50566tfckrair/tmpt7vkfxm_ /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py\n', b'')
<<host-ip>> ESTABLISH SSH CONNECTION FOR USER: <user>
<<host-ip>> SSH: EXEC sshpass -d52 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="<user>"' -o ConnectTimeout=10 -o 'ControlPath="<user-home-dir>.ansible/cp/8293f2b576"' <host-ip> '/bin/sh -c '"'"'chmod u+x /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/ /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py && sleep 0'"'"''
<<host-ip>> (0, b'', b'')
<<host-ip>> ESTABLISH SSH CONNECTION FOR USER: <user>
<<host-ip>> SSH: EXEC sshpass -d52 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="<user>"' -o ConnectTimeout=10 -o 'ControlPath="<user-home-dir>.ansible/cp/8293f2b576"' -tt <host-ip> '/bin/sh -c '"'"'/usr/bin/python3 /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py && sleep 0'"'"''
<<host-ip>> (1, b'Traceback (most recent call last):\r\n  File "/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py", line 107, in <module>\r\n    _ansiballz_main()\r\n  File "/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py", line 47, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.community.general.plugins.modules.homebrew_cask\', init_globals=dict(_module_fqn=\'ansible_collections.community.general.plugins.modules.homebrew_cask\', _modlib_path=modlib_path),\r\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 895, in <module>\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 887, in main\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 450, in run\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 523, in _run\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 671, in _install_casks\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 622, in _install_current_cask\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 485, in _current_cask_is_installed\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 513, in _brew_cask_command_is_deprecated\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py", line 78, in __ge__\r\n  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py", line 338, in _cmp\r\nTypeError: \'<\' not supported between instances of \'str\' and \'int\'\r\n', b'Shared connection to <host-ip> closed.\r\n')
<<host-ip>> Failed to connect to the host via ssh: Shared connection to <host-ip> closed.
<<host-ip>> ESTABLISH SSH CONNECTION FOR USER: <user>
<<host-ip>> SSH: EXEC sshpass -d52 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="<user>"' -o ConnectTimeout=10 -o 'ControlPath="<user-home-dir>.ansible/cp/8293f2b576"' <host-ip> '/bin/sh -c '"'"'rm -f -r /Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/ > /dev/null 2>&1 && sleep 0'"'"''
<<host-ip>> (0, b'', b'')
The full traceback is:
Traceback (most recent call last):
  File "/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.homebrew_cask', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.homebrew_cask', _modlib_path=modlib_path),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 895, in <module>
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 887, in main
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 450, in run
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 523, in _run
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 671, in _install_casks
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 622, in _install_current_cask
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 485, in _current_cask_is_installed
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 513, in _brew_cask_command_is_deprecated
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py", line 78, in __ge__
  File "/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py", line 338, in _cmp
TypeError: '<' not supported between instances of 'str' and 'int'
failed: [JHQHAK010006MD] (item={'name': 'android-platform-tools', 'install_options': 'debug'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "install_options": "debug",
        "name": "android-platform-tools"
    },
    "module_stderr": "Shared connection to <host-ip> closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/Users/<user>/.ansible/tmp/ansible-tmp-1708063976.388025-51090-165256968901751/AnsiballZ_homebrew_cask.py\", line 47, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.homebrew_cask', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.homebrew_cask', _modlib_path=modlib_path),\r\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 210, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 895, in <module>\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 887, in main\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 450, in run\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 523, in _run\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 671, in _install_casks\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 622, in _install_current_cask\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 485, in _current_cask_is_installed\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py\", line 513, in _brew_cask_command_is_deprecated\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py\", line 78, in __ge__\r\n  File \"/var/folders/q9/3tcdjq597cv45fmbv3nn4mjwx4g9jp/T/ansible_homebrew_cask_payload_wbe8309i/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py\", line 338, in _cmp\r\nTypeError: '<' not supported between instances of 'str' and 'int'\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
</details>

As a workaround I install directly with:

```yml
- name: Install Android Platform Tools
  homebrew_cask:
    name: 'android-platform-tools'
    state: present
    install_options: 'quiet'
    sudo_password: '{{ ansible_become_password | default(omit) }}'

```

**Comment by excalq** [comment]
Getting the same fatal error, when running `mac-dev-playbook`, on a completely fresh MacBook M1 running Sonoma 14.3.1. The same error repeats for each `homebrew_cask_apps` in `config.yml`. Unclear how to workaround or proceed. 

## Error Reported 
```
TASK [geerlingguy.mac.homebrew : Install configured cask applications.] **********************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: '<' not supported between instances of 'str' and 'int'
failed: [127.0.0.1] (item=docker) => changed=false 
  ansible_loop_var: item
  item: docker
  module_stderr: |-
    Traceback (most recent call last):
      File "/Users/arthur/.ansible/tmp/ansible-tmp-1708469930.622443-5587-245938492723656/AnsiballZ_homebrew_cask.py", line 107, in <module>
        _ansiballz_main()
      File "/Users/arthur/.ansible/tmp/ansible-tmp-1708469930.622443-5587-245938492723656/AnsiballZ_homebrew_cask.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/Users/arthur/.ansible/tmp/ansible-tmp-1708469930.622443-5587-245938492723656/AnsiballZ_homebrew_cask.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.general.plugins.modules.homebrew_cask', init_globals=dict(_module_fqn='ansible_collections.community.general.plugins.modules.homebrew_cask', _modlib_path=modlib_path),
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 895, in <module>
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 887, in main
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 450, in run
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 523, in _run
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 671, in _install_casks
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 622, in _install_current_cask
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 485, in _current_cask_is_installed
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible_collections/community/general/plugins/modules/homebrew_cask.py", line 513, in _brew_cask_command_is_deprecated
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py", line 78, in __ge__
      File "/var/folders/9n/wgtj2qt1631bw_sywp_w0x3w0000gp/T/ansible_homebrew_cask_payload_w75x72lg/ansible_homebrew_cask_payload.zip/ansible/module_utils/compat/version.py", line 338, in _cmp
    TypeError: '<' not supported between instances of 'str' and 'int'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

## Code Location
Grepping for the task description leads me to line 141 in the collection role:
```
    - name: Install configured cask applications.
      homebrew_cask:
        name: "{{ item.name | default(item) }}"
        state: present
        install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
        accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
        sudo_password: "{{ ansible_become_password | default(omit) }}"
      loop: "{{ homebrew_cask_apps }}"
      notify:
        - Clear homebrew cache
```

**Comment by excalq** [comment]
Possibly related to https://github.com/ansible-collections/community.general/issues/4708#issuecomment-1140392900?

**Comment by mark-omarov** [comment]
Giving it a look on the go. It does look like underlying issue with the `community.general` version compatibility check rather than this collection. I'll take another look by the end of the week and potentially close this issue in favor of mentioned by @excalq.

**Comment by excalq** [comment]
Having given up, and manually running `brew install visual-studio-code` caused Homebrew to also update itself, which fixed the root cause. Previously `brew version` reported `Homebrew >=4.1.0 (shallow or no git repository)`. Now it reports `Homebrew 4.2.9`.

So I suppose issuing a `brew update --auto-update` before using Cask for the first time would help prevent this issue on a new MacOS install.
